CREATE TABLE "CUSTOMER" (
    "ID" NUMBER(19) NOT NULL,
    "FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL,
    "LAST_NAME" VARCHAR2(255 CHAR) NOT NULL,
    "BIRTH_DATE" DATE,
    "ADDRESS" VARCHAR2(50 CHAR),
    "COUNTRY" VARCHAR2(255 CHAR),
    "POSTAL_CODE" NUMBER(10),
    "PHONE_NUMBER" VARCHAR2(255 CHAR),
    "KIDS" NUMBER(2),
    PRIMARY KEY(ID)
);
